export const validAnalysisResult = {
  schemaVersion: "1.1",
  outputLanguage: "ru",
  sourceLanguage: "lv",
  documentType: { value: "Уведомление", status: "found", evidenceIds: ["e1"], confidence: "high", basis: "fact" },
  sender: { value: null, status: "not_found", evidenceIds: [], confidence: "low", basis: "fact" },
  summary: "Документ сообщает о проверке данных.",
  requiredActions: [],
  deadlines: [{ dateText: "20.07.2026 plkst. 14.00", normalizedDate: "2026-07-20", meaning: "Ierasties uz tikšanos", status: "found", evidenceIds: ["e2"], confidence: "high", basis: "fact" }],
  events: [{ id: "event_1", title: "Ierasties uz tikšanos", kind: "meeting", dateText: "20.07.2026 plkst. 14.00", localDate: "2026-07-20", localTime: "14:00", documentTimeZone: null, location: null, status: "found", evidenceIds: ["e2"], confidence: "high", basis: "fact" }],
  requiredDocuments: [],
  consequencesOfInaction: [],
  actionPlan: [{ step: 1, action: "Проверить контактные данные организации.", evidenceIds: [], confidence: "medium", basis: "inference" }],
  replyNeeded: "unclear",
  suggestedReply: null,
  evidence: [{ id: "e1", quote: "Уведомление", location: "Страница 1", supports: ["documentType"] }, { id: "e2", quote: "20.07.2026 plkst. 14.00", location: "Страница 1", supports: ["deadlines", "events"] }],
  uncertainties: ["Отправитель не найден."],
  confidence: "medium",
  safetyNotice: "Это информационное объяснение, а не профессиональная консультация.",
};
