import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { assessStudioReadiness, parseStudioRequest, validateGeneratedDocument } from "../app/document-studio-schema.ts";
import { documentDocx } from "../app/document-export.ts";
import { STUDIO_LIMITS } from "../app/document-studio-store.ts";

const base={mode:"create",templateId:"lease",country:"Latvia",region:"Riga",outputLanguage:"en",confirmedInsufficient:false,details:{landlord:"A",tenant:"B",property:"Riga",rent:"800 EUR",start:"2026-08-01",end:"",notes:""}};
test("underspecified legal drafts are never marked ready",()=>{const weak=parseStudioRequest({...base,details:{}}),partial=parseStudioRequest(base),ready=parseStudioRequest({...base,details:{...base.details,end:"2027-08-01",notes:"Deposit and utility terms supplied"}});assert.ok(weak&&partial&&ready);assert.equal(assessStudioReadiness(weak).level,"red");assert.equal(assessStudioReadiness(partial).level,"yellow");assert.equal(assessStudioReadiness(ready).level,"green")});
test("generated result and real DOCX export validate",()=>{const result={schemaVersion:"1.0",title:"Lease",mode:"create",templateId:"lease",country:"Latvia",region:"Riga",outputLanguage:"en",readiness:{level:"green",score:100,missingCritical:[],missingHelpful:[]},sections:[{heading:"Parties",body:"A and B"}],plainText:"Lease\nA and B",assumptions:[],changes:[],unresolvedIssues:[],legalSources:[],reviewChecklist:[],confidence:"medium",safetyNotice:"Review before use"};assert.equal(validateGeneratedDocument(result),true);assert.deepEqual([...documentDocx(result).slice(0,2)],[80,75]);assert.equal(validateGeneratedDocument({...result,region:42}),false);assert.equal(validateGeneratedDocument({...result,readiness:{...result.readiness,score:101}}),false)});
test("studio plans have deliberately bounded generation limits",()=>{assert.deepEqual(STUDIO_LIMITS.free,{day:1,month:3,words:3500});assert.deepEqual(STUDIO_LIMITS.pro,{day:30,month:300,words:12000})});
test("unknown templates and jurisdictions are rejected",()=>{assert.equal(parseStudioRequest({...base,templateId:"invented"}),null);assert.equal(parseStudioRequest({...base,country:"Neverland"}),null)});
test("server pins Luna, low reasoning, auth, structured output, and no retention",async()=>{const route=await readFile(new URL("../app/api/document-studio/route.ts",import.meta.url),"utf8");for(const p of [/gpt-5\.6-luna/,/effort:\"low\"/,/verifySupabaseRequest/,/generatedDocumentJsonSchema/,/store:false/,/activePlanForUser/])assert.match(route,p)});
test("studio file uploads reuse signature checks and map every supported input kind",async()=>{const route=await readFile(new URL("../app/api/document-studio/route.ts",import.meta.url),"utf8");for(const p of [/request\.formData\(\)/,/validateDocumentFile\(uploaded\)/,/hasValidDocumentSignature\(uploaded\.name,bytes\)/,/type:\"input_file\"/,/type:\"input_image\"/,/decodeTextDocument\(bytes\)/,/costKind/])assert.match(route,p)});
test("studio timeout leaves three minutes for jurisdiction-aware generation",async()=>{const route=await readFile(new URL("../app/api/document-studio/route.ts",import.meta.url),"utf8");assert.match(route,/STUDIO_REQUEST_TIMEOUT_MS\s*=\s*180_000/);assert.match(route,/setTimeout\(\(\)=>controller\.abort\(\),STUDIO_REQUEST_TIMEOUT_MS\)/)});
