export type StudioGuideLocale = "en" | "ru" | "lv";

type Localized = Record<StudioGuideLocale, string>;
export type StudioGuideField = {
  key: string;
  question: Localized;
  example: Localized;
  required: boolean;
  multiline?: boolean;
};
export type StudioTemplateGuide = { intro: Localized; fields: StudioGuideField[] };

const l = (en: string, ru: string, lv: string): Localized => ({ en, ru, lv });
const f = (key: string, required: boolean, question: Localized, example: Localized, multiline = false): StudioGuideField => ({ key, required, question, example, multiline });

const party = f("parties", true, l("Who are all parties, and what is each party's role?", "Кто участвует и какова роль каждой стороны?", "Kas ir visas puses un kāda ir katras puses loma?"), l("Use full legal names; add company numbers or addresses if relevant.", "Укажите полные имена или названия; при необходимости — регистрационные номера и адреса.", "Norādiet pilnus juridiskos nosaukumus; ja vajag, arī reģistrācijas numurus un adreses."));
const law = f("governingLaw", false, l("Is a governing law, court, or dispute process required?", "Нужно ли указать применимое право, суд или порядок разрешения споров?", "Vai jānorāda piemērojamie tiesību akti, tiesa vai strīdu kārtība?"), l("If unsure, leave this blank; the draft will mark it for local review.", "Если не знаете — оставьте пустым: документ отметит это для местной проверки.", "Ja nezināt, atstājiet tukšu; melnraksts to atzīmēs vietējai pārbaudei."));
const extra = f("additionalTerms", false, l("Are there any special conditions, exceptions, or facts?", "Есть ли особые условия, исключения или важные факты?", "Vai ir īpaši noteikumi, izņēmumi vai svarīgi fakti?"), l("Include anything that should not be assumed by the AI.", "Добавьте всё, что ИИ не должен додумывать самостоятельно.", "Pievienojiet visu, ko AI nedrīkst pieņemt pats."), true);

export const studioTemplateGuides: Record<string, StudioTemplateGuide> = {
  lease: { intro: l("A strong lease needs the parties, property, money, term, responsibilities, and exit rules.", "Для полноценной аренды нужны стороны, объект, деньги, срок, обязанности и правила расторжения.", "Pilnvērtīgam īres līgumam vajag puses, īpašumu, maksājumus, termiņu, pienākumus un izbeigšanas kārtību."), fields: [
    party,
    f("property", true, l("What property is being rented?", "Какой объект сдаётся в аренду?", "Kāds īpašums tiek izīrēts?"), l("Full address, unit, included rooms, parking or storage.", "Полный адрес, квартира/помещение, парковка или кладовая.", "Pilna adrese, telpas, stāvvieta vai noliktava.")),
    f("term", true, l("When does the lease start and end?", "Когда аренда начинается и заканчивается?", "Kad īre sākas un beidzas?"), l("State whether it is fixed-term or open-ended and include handover date.", "Укажите срочный или бессрочный договор и дату передачи объекта.", "Norādiet, vai termiņš ir noteikts vai nenoteikts, un nodošanas datumu.")),
    f("payment", true, l("What are the rent, currency, due date, and payment method?", "Каковы аренда, валюта, срок и способ оплаты?", "Kāda ir īres maksa, valūta, termiņš un maksāšanas veids?"), l("Example: EUR 850 by bank transfer before the 5th of each month.", "Например: 850 EUR переводом до 5-го числа каждого месяца.", "Piemēram: 850 EUR ar pārskaitījumu līdz katra mēneša 5. datumam.")),
    f("deposit", false, l("Is there a security deposit and when is it returned?", "Есть ли залог и когда он возвращается?", "Vai ir drošības depozīts un kad tas tiek atmaksāts?"), l("Amount, permitted deductions, inspection, and return deadline.", "Сумма, допустимые удержания, осмотр и срок возврата.", "Summa, atļautie ieturējumi, apskate un atmaksas termiņš.")),
    f("utilities", false, l("Who pays utilities and recurring charges?", "Кто оплачивает коммунальные и регулярные расходы?", "Kas maksā komunālos un regulāros izdevumus?"), l("List electricity, heating, internet, management fees, taxes, and meters.", "Перечислите электричество, отопление, интернет, обслуживание, налоги и счётчики.", "Uzskaitiet elektrību, apkuri, internetu, apsaimniekošanu, nodokļus un skaitītājus.")),
    f("responsibilities", false, l("Who handles repairs, maintenance, guests, pets, and alterations?", "Кто отвечает за ремонт, обслуживание, гостей, животных и изменения объекта?", "Kas atbild par remontu, uzturēšanu, viesiem, dzīvniekiem un pārbūvi?"), l("Describe permissions, limits, inspection access, and notice.", "Опишите разрешения, ограничения, доступ для осмотра и уведомления.", "Aprakstiet atļaujas, ierobežojumus, apskates piekļuvi un paziņošanu."), true),
    f("termination", false, l("How may either party end or renew the lease?", "Как каждая сторона может прекратить или продлить аренду?", "Kā katra puse var izbeigt vai pagarināt īri?"), l("Notice period, breach, early exit, renewal, and key return.", "Срок уведомления, нарушения, досрочный выход, продление и возврат ключей.", "Paziņošanas termiņš, pārkāpumi, pirmstermiņa izbeigšana, pagarināšana un atslēgu atdošana.")),
    law, extra,
  ]},
  service: { intro: l("Define exactly what will be delivered, when, for how much, and how completion is accepted.", "Точно опишите результат, сроки, цену и порядок приёмки.", "Precīzi aprakstiet rezultātu, termiņus, cenu un pieņemšanas kārtību."), fields: [party,
    f("scope", true, l("What services are included and excluded?", "Какие услуги входят и не входят в договор?", "Kādi pakalpojumi ir iekļauti un izslēgti?"), l("List concrete tasks and boundaries.", "Перечислите конкретные задачи и границы работ.", "Uzskaitiet konkrētus uzdevumus un robežas."), true),
    f("deliverables", true, l("What tangible deliverables must be provided?", "Какие конкретные результаты должны быть переданы?", "Kādi konkrēti rezultāti jānodod?"), l("Files, reports, sessions, quantities, formats, or quality standards.", "Файлы, отчёты, встречи, объём, форматы или стандарты качества.", "Faili, ziņojumi, sesijas, apjomi, formāti vai kvalitātes standarti."), true),
    f("schedule", true, l("What are the start date, milestones, and final deadline?", "Каковы дата начала, этапы и конечный срок?", "Kāds ir sākuma datums, posmi un gala termiņš?"), l("Include dependencies and what happens if a party causes delay.", "Добавьте зависимости и последствия задержки по вине стороны.", "Norādiet atkarības un sekas, ja puse izraisa kavējumu.")),
    f("fees", true, l("How much, when, and on what conditions is payment due?", "Сколько, когда и при каких условиях нужно платить?", "Cik, kad un ar kādiem nosacījumiem jāmaksā?"), l("Currency, tax, deposit, invoice dates, expenses, and late payment.", "Валюта, налоги, аванс, счета, расходы и просрочка.", "Valūta, nodokļi, avanss, rēķini, izdevumi un kavējums.")),
    f("acceptance", false, l("How will the client accept or reject the work?", "Как заказчик принимает или отклоняет работу?", "Kā klients pieņem vai noraida darbu?"), l("Review period, objective criteria, corrections, and deemed acceptance.", "Срок проверки, критерии, исправления и автоматическая приёмка.", "Pārbaudes termiņš, kritēriji, labojumi un automātiska pieņemšana.")),
    f("rights", false, l("Who owns intellectual property and confidential material?", "Кому принадлежат права и конфиденциальные материалы?", "Kam pieder intelektuālais īpašums un konfidenciālie materiāli?"), l("Clarify pre-existing materials, licences, portfolio use, and secrecy.", "Уточните исходные материалы, лицензии, портфолио и конфиденциальность.", "Precizējiet iepriekšējos materiālus, licences, portfolio un konfidencialitāti.")),
    f("termination", false, l("How can the agreement be changed or ended?", "Как изменить или прекратить договор?", "Kā līgumu var mainīt vai izbeigt?"), l("Notice, unpaid work, handover, refunds, and surviving clauses.", "Уведомление, незавершённая работа, передача, возврат денег и сохраняющиеся условия.", "Paziņošana, nepabeigtais darbs, nodošana, atmaksas un spēkā paliekošie noteikumi.")), law, extra,
  ]},
  nda: { intro: l("An NDA must identify the protected information, permitted purpose, exceptions, duration, and remedies.", "NDA должен определять защищённую информацию, допустимую цель, исключения, срок и последствия нарушения.", "NDA jānosaka aizsargātā informācija, atļautais mērķis, izņēmumi, termiņš un sekas."), fields: [party,
    f("purpose", true, l("Why will confidential information be shared?", "Для какой цели передаётся конфиденциальная информация?", "Kādam mērķim tiks izpausta konfidenciāla informācija?"), l("State the project, negotiation, employment, or evaluation purpose.", "Укажите проект, переговоры, трудовые отношения или оценку.", "Norādiet projektu, sarunas, darba attiecības vai izvērtēšanu.")),
    f("confidentialInfo", true, l("What information must be protected?", "Какую информацию нужно защищать?", "Kāda informācija jāaizsargā?"), l("Categories, formats, oral disclosures, marking rules, and personal data.", "Категории, форматы, устные сведения, маркировка и персональные данные.", "Kategorijas, formāti, mutiski paziņojumi, marķēšana un personas dati."), true),
    f("permittedUse", true, l("Who may use or receive it, and for what purpose?", "Кто и для чего может использовать или получать информацию?", "Kas un kādam mērķim drīkst to lietot vai saņemt?"), l("Employees, advisers, subcontractors, security duties, and need-to-know limits.", "Сотрудники, консультанты, подрядчики, безопасность и принцип необходимости.", "Darbinieki, konsultanti, apakšuzņēmēji, drošība un nepieciešamības princips."), true),
    f("exceptions", false, l("Which standard exclusions should apply?", "Какие стандартные исключения должны действовать?", "Kādi standarta izņēmumi jāpiemēro?"), l("Public, already known, independently developed, lawfully received, or legally compelled.", "Публичная, ранее известная, независимо созданная, законно полученная или раскрываемая по закону информация.", "Publiska, jau zināma, neatkarīgi radīta, likumīgi saņemta vai obligāti izpaužama informācija.")),
    f("duration", true, l("How long do the agreement and confidentiality duties last?", "Как долго действуют соглашение и обязанность сохранять тайну?", "Cik ilgi darbojas līgums un konfidencialitātes pienākumi?"), l("Give separate dates if trade secrets need longer protection.", "Укажите отдельный срок, если коммерческие тайны защищаются дольше.", "Norādiet atsevišķu termiņu, ja komercnoslēpumi jāaizsargā ilgāk.")),
    f("returnDelete", false, l("When must information be returned or deleted?", "Когда информацию нужно вернуть или удалить?", "Kad informācija jāatdod vai jādzēš?"), l("Include backups, legal retention, and written confirmation.", "Укажите резервные копии, обязательное хранение и письменное подтверждение.", "Norādiet rezerves kopijas, obligāto glabāšanu un rakstisku apliecinājumu.")), law, extra,
  ]},
  loan: { intro: l("Record the money, transfer, repayment, interest, security, default rules, and applicable law.", "Зафиксируйте сумму, передачу, возврат, проценты, обеспечение, просрочку и применимое право.", "Fiksējiet summu, nodošanu, atmaksu, procentus, nodrošinājumu, kavējumu un piemērojamos tiesību aktus."), fields: [party,
    f("principal", true, l("What amount and currency will be lent?", "Какая сумма и валюта передаются в долг?", "Kāda summa un valūta tiek aizdota?"), l("Use exact figures and words if required.", "Укажите точную сумму; при необходимости — также прописью.", "Norādiet precīzu summu; ja vajag, arī vārdiem.")),
    f("funding", true, l("When and how will the money be transferred?", "Когда и как будут переданы деньги?", "Kad un kā nauda tiks pārskaitīta?"), l("Date, bank transfer or cash, account, and proof of payment.", "Дата, перевод или наличные, счёт и подтверждение передачи.", "Datums, pārskaitījums vai skaidra nauda, konts un maksājuma pierādījums.")),
    f("repayment", true, l("What is the repayment schedule?", "Каков график возврата?", "Kāds ir atmaksas grafiks?"), l("Single date or instalments, amounts, due dates, and early repayment.", "Одна дата или платежи, суммы, сроки и досрочный возврат.", "Viens datums vai maksājumi, summas, termiņi un pirmstermiņa atmaksa."), true),
    f("interest", false, l("Is interest charged and how is it calculated?", "Начисляются ли проценты и как они рассчитываются?", "Vai tiek piemēroti procenti un kā tos aprēķina?"), l("Rate, fixed or variable basis, calculation period, and legal cap review.", "Ставка, фиксированная/переменная база, период расчёта и проверка законного предела.", "Likme, fiksēta vai mainīga bāze, periods un likumīgā ierobežojuma pārbaude.")),
    f("security", false, l("Is the loan secured or guaranteed?", "Есть ли залог или поручитель?", "Vai aizdevums ir nodrošināts vai garantēts?"), l("Describe collateral, guarantor, valuation, release, and registration.", "Опишите обеспечение, поручителя, оценку, освобождение и регистрацию.", "Aprakstiet nodrošinājumu, galvinieku, novērtējumu, atbrīvošanu un reģistrāciju.")),
    f("default", false, l("What happens after late payment or another default?", "Что происходит при просрочке или другом нарушении?", "Kas notiek maksājuma kavējuma vai cita pārkāpuma gadījumā?"), l("Grace period, notice, lawful fees, acceleration, and enforcement.", "Льготный срок, уведомление, допустимые комиссии, досрочное требование и взыскание.", "Papildu termiņš, paziņojums, atļautās maksas, paātrinājums un piedziņa.")), law, extra,
  ]},
  power: { intro: l("A power of attorney needs precise authority, limits, duration, and local form requirements.", "Для доверенности нужны точные полномочия, ограничения, срок и местные требования к форме.", "Pilnvarai vajag precīzas tiesības, ierobežojumus, termiņu un vietējās formas prasības."), fields: [
    f("principal", true, l("Who grants the authority?", "Кто выдаёт доверенность?", "Kas piešķir pilnvarojumu?"), l("Full name, identity details, and address only where necessary.", "Полное имя, необходимые данные документа и адрес.", "Pilns vārds, nepieciešamie identitātes dati un adrese.")),
    f("agent", true, l("Who receives the authority?", "Кто получает полномочия?", "Kas saņem pilnvarojumu?"), l("Full name, identity details, address, and relationship.", "Полное имя, данные документа, адрес и связь с доверителем.", "Pilns vārds, identitātes dati, adrese un saistība ar pilnvarotāju.")),
    f("powers", true, l("What exact actions may the agent perform?", "Какие именно действия может совершать представитель?", "Kādas precīzas darbības pilnvarnieks drīkst veikt?"), l("Name institutions, assets, transactions, signatures, and monetary limits.", "Назовите учреждения, имущество, сделки, подписи и денежные пределы.", "Nosauciet iestādes, īpašumu, darījumus, parakstus un naudas limitus."), true),
    f("limits", false, l("What is expressly forbidden or requires prior approval?", "Что прямо запрещено или требует предварительного согласия?", "Kas ir skaidri aizliegts vai prasa iepriekšēju piekrišanu?"), l("Self-dealing, gifts, sale limits, delegation, or specific exclusions.", "Сделки с собой, подарки, предел продажи, передоверие и исключения.", "Darījumi ar sevi, dāvanas, pārdošanas limiti, pārpilnvarojums un izņēmumi."), true),
    f("duration", true, l("When does authority begin and end?", "Когда полномочия начинаются и заканчиваются?", "Kad pilnvarojums sākas un beidzas?"), l("Date, event, revocation method, incapacity, and survival if relevant.", "Дата, событие, отзыв, недееспособность и сохранение полномочий.", "Datums, notikums, atsaukšana, rīcībnespēja un spēkā palikšana.")),
    f("formalities", false, l("Does it need a witness, notary, apostille, or registration?", "Нужны ли свидетели, нотариус, апостиль или регистрация?", "Vai vajag liecinieku, notāru, apostille vai reģistrāciju?"), l("If unknown, tell us the authority where it will be used.", "Если не знаете, укажите орган или организацию, где документ будет использоваться.", "Ja nezināt, norādiet iestādi, kur dokuments tiks izmantots.")), law, extra,
  ]},
  complaint: { intro: l("A persuasive complaint is chronological, evidenced, specific about the remedy, and sent to the right recipient.", "Убедительная жалоба излагает события по порядку, с доказательствами и конкретным требованием.", "Pārliecinoša sūdzība izklāsta notikumus secīgi, ar pierādījumiem un konkrētu prasījumu."), fields: [
    f("senderRecipient", true, l("Who is complaining, and who should receive it?", "Кто жалуется и кому адресована жалоба?", "Kas iesniedz sūdzību un kam tā adresēta?"), l("Names, organisation, department, reference or account number.", "Имена, организация, отдел, номер дела или счёта.", "Vārdi, organizācija, nodaļa, lietas vai konta numurs.")),
    f("events", true, l("What happened, in chronological order?", "Что произошло — по порядку и с датами?", "Kas notika hronoloģiskā secībā?"), l("Dates, people, promises, actions, and exact words where important.", "Даты, люди, обещания, действия и точные формулировки, если они важны.", "Datumi, personas, solījumi, darbības un precīzi vārdi, ja svarīgi."), true),
    f("evidence", false, l("What evidence or attachments support the complaint?", "Какие доказательства или приложения подтверждают жалобу?", "Kādi pierādījumi vai pielikumi pamato sūdzību?"), l("Contracts, receipts, emails, photos, names of witnesses, case numbers.", "Договоры, чеки, письма, фото, свидетели, номера обращений.", "Līgumi, čeki, e-pasti, foto, liecinieki, lietu numuri."), true),
    f("previousSteps", false, l("What have you already tried, and what response did you receive?", "Что вы уже предпринимали и какой получили ответ?", "Ko jau mēģinājāt un kādu atbildi saņēmāt?"), l("Calls, visits, prior complaints, dates, and outcomes.", "Звонки, визиты, прежние жалобы, даты и результаты.", "Zvani, vizītes, iepriekšējās sūdzības, datumi un rezultāti."), true),
    f("remedy", true, l("What exact outcome do you request?", "Какого конкретного результата вы требуете?", "Kādu konkrētu rezultātu pieprasāt?"), l("Refund, correction, explanation, repair, apology, or action by a date.", "Возврат, исправление, объяснение, ремонт, извинение или действие к сроку.", "Atmaksa, labojums, skaidrojums, remonts, atvainošanās vai darbība līdz datumam.")),
    f("deadline", false, l("By when should they reply, and how?", "До какого срока и каким способом нужен ответ?", "Līdz kuram datumam un kā jāatbild?"), l("Use a reasonable deadline and preferred email or postal address.", "Укажите разумный срок и предпочитаемый email или почтовый адрес.", "Norādiet saprātīgu termiņu un vēlamo e-pastu vai pasta adresi.")), law, extra,
  ]},
  request: { intro: l("An official request should identify the authority, the request, its basis, evidence, and desired response.", "Официальное заявление должно содержать адресата, просьбу, основание, доказательства и желаемый ответ.", "Oficiālā iesniegumā jānorāda adresāts, lūgums, pamatojums, pierādījumi un vēlamā atbilde."), fields: [party,
    f("recipient", true, l("Which authority, organisation, or person should receive it?", "Какому органу, организации или человеку оно адресовано?", "Kurai iestādei, organizācijai vai personai tas adresēts?"), l("Official name, department, address, and reference number.", "Официальное название, отдел, адрес и номер дела.", "Oficiālais nosaukums, nodaļa, adrese un lietas numurs.")),
    f("request", true, l("What exact action or information are you requesting?", "Какое конкретное действие или информацию вы просите?", "Kādu konkrētu darbību vai informāciju pieprasāt?"), l("Write one clear requested outcome and any alternatives.", "Сформулируйте один чёткий результат и возможные альтернативы.", "Formulējiet vienu skaidru rezultātu un iespējamās alternatīvas."), true),
    f("background", true, l("What facts and dates explain the request?", "Какие факты и даты объясняют просьбу?", "Kādi fakti un datumi izskaidro lūgumu?"), l("Give a short chronology without speculation.", "Дайте краткую хронологию без предположений.", "Sniedziet īsu hronoloģiju bez pieņēmumiem."), true),
    f("evidence", false, l("Which documents, records, or references support it?", "Какие документы, записи или ссылки это подтверждают?", "Kādi dokumenti, ieraksti vai atsauces to pamato?"), l("List attachments and identifiers; do not paste unnecessary sensitive data.", "Перечислите приложения и номера; не добавляйте лишние чувствительные данные.", "Uzskaitiet pielikumus un identifikatorus; nepievienojiet liekus sensitīvus datus."), true),
    f("response", false, l("When and how should a response be sent?", "Когда и каким способом должен прийти ответ?", "Kad un kā jānosūta atbilde?"), l("Email, post, portal, language, and any known statutory deadline.", "Email, почта, портал, язык и известный установленный срок.", "E-pasts, pasts, portāls, valoda un zināms likuma termiņš.")), law, extra,
  ]},
  termination: { intro: l("Identify the underlying agreement, legal or contractual basis, notice period, effective date, and final obligations.", "Укажите исходный договор, основание, срок уведомления, дату прекращения и финальные обязанности.", "Norādiet sākotnējo līgumu, pamatu, paziņošanas termiņu, beigu datumu un gala pienākumus."), fields: [party,
    f("agreement", true, l("Which agreement or relationship is being terminated?", "Какой договор или отношения прекращаются?", "Kurš līgums vai attiecības tiek izbeigtas?"), l("Title, date, reference number, subject, and relevant clause.", "Название, дата, номер, предмет и соответствующий пункт.", "Nosaukums, datums, numurs, priekšmets un attiecīgais punkts.")),
    f("basis", true, l("Why and under which clause or rule is it ending?", "Почему и на основании какого пункта или правила происходит прекращение?", "Kāpēc un saskaņā ar kuru punktu vai noteikumu tas tiek izbeigts?"), l("Ordinary notice, breach, mutual agreement, expiry, or another verified basis.", "Обычное уведомление, нарушение, соглашение сторон, истечение срока или иное подтверждённое основание.", "Parasts paziņojums, pārkāpums, pušu vienošanās, termiņa beigas vai cits pārbaudīts pamats.")),
    f("dates", true, l("When is notice sent and when should termination take effect?", "Когда направляется уведомление и когда прекращение вступает в силу?", "Kad paziņojums tiek nosūtīts un kad izbeigšana stājas spēkā?"), l("Include the required notice period and delivery method.", "Укажите требуемый срок уведомления и способ доставки.", "Norādiet vajadzīgo paziņošanas termiņu un piegādes veidu.")),
    f("closing", false, l("What must each party do before or after termination?", "Что каждая сторона должна сделать до или после прекращения?", "Kas katrai pusei jāizdara pirms vai pēc izbeigšanas?"), l("Final payment, return of property, access removal, handover, confidentiality.", "Финальный расчёт, возврат имущества, отключение доступа, передача дел, конфиденциальность.", "Gala maksājums, mantas atdošana, piekļuves slēgšana, nodošana, konfidencialitāte."), true), law, extra,
  ]},
  letter: { intro: l("A clear formal letter needs the sender, recipient, subject, verified facts, requested action, tone, and deadline.", "Для делового письма нужны отправитель, адресат, тема, факты, требуемое действие, тон и срок.", "Oficiālai vēstulei vajag sūtītāju, adresātu, tematu, faktus, prasīto darbību, toni un termiņu."), fields: [
    f("senderRecipient", true, l("Who sends the letter, and who receives it?", "Кто отправитель и кто адресат?", "Kas sūta vēstuli un kas to saņem?"), l("Names, roles, organisation, contact details, and reference number.", "Имена, должности, организация, контакты и номер дела.", "Vārdi, amati, organizācija, kontakti un lietas numurs.")),
    f("subject", true, l("What is the letter about in one sentence?", "О чём письмо — одним предложением?", "Par ko ir vēstule vienā teikumā?"), l("Use a concrete subject that the recipient can route correctly.", "Сформулируйте конкретную тему, чтобы письмо попало нужному человеку.", "Formulējiet konkrētu tematu, lai vēstule nonāktu pie pareizā cilvēka.")),
    f("facts", true, l("Which verified facts must the letter state?", "Какие подтверждённые факты нужно изложить?", "Kādi pārbaudīti fakti jānorāda?"), l("Dates, amounts, correspondence, agreements, and identifiers.", "Даты, суммы, переписка, договорённости и номера.", "Datumi, summas, sarakste, vienošanās un identifikatori."), true),
    f("requestedAction", true, l("What should the recipient do or understand?", "Что адресат должен сделать или понять?", "Kas adresātam jādara vai jāsaprot?"), l("State one primary request and a reasonable deadline.", "Укажите одну основную просьбу и разумный срок.", "Norādiet vienu galveno lūgumu un saprātīgu termiņu.")),
    f("tone", false, l("What tone and relationship should the letter preserve?", "Какой тон и отношения нужно сохранить?", "Kāds tonis un attiecības jāsaglabā?"), l("Neutral, firm, warm, apologetic, diplomatic, or concise.", "Нейтральный, твёрдый, тёплый, извиняющийся, дипломатичный или краткий.", "Neitrāls, stingrs, silts, atvainojošs, diplomātisks vai īss.")), extra,
  ]},
  proposal: { intro: l("A commercial proposal should connect the client's problem to a specific solution, scope, price, timeline, and decision path.", "Коммерческое предложение должно связать задачу клиента с решением, объёмом, ценой, сроками и следующим шагом.", "Komerciālam piedāvājumam jāsasaista klienta problēma ar risinājumu, apjomu, cenu, termiņiem un nākamo soli."), fields: [party,
    f("problem", true, l("What problem or opportunity does the client have?", "Какую проблему или возможность имеет клиент?", "Kāda ir klienta problēma vai iespēja?"), l("Use the client's own context, current situation, and measurable impact.", "Используйте контекст клиента, текущую ситуацию и измеримый эффект.", "Izmantojiet klienta kontekstu, pašreizējo situāciju un izmērāmu ietekmi."), true),
    f("solution", true, l("What solution do you propose and why is it suitable?", "Какое решение вы предлагаете и почему оно подходит?", "Kādu risinājumu piedāvājat un kāpēc tas ir piemērots?"), l("Method, differentiators, expected outcome, and limitations.", "Метод, отличия, ожидаемый результат и ограничения.", "Metode, priekšrocības, sagaidāmais rezultāts un ierobežojumi."), true),
    f("scope", true, l("What is included, excluded, and delivered?", "Что входит, не входит и будет передано?", "Kas ir iekļauts, izslēgts un nododams?"), l("Packages, quantities, deliverables, revisions, and client responsibilities.", "Пакеты, объём, результаты, правки и обязанности клиента.", "Paketes, apjoms, rezultāti, labojumi un klienta pienākumi."), true),
    f("price", true, l("What are the price, currency, taxes, and payment schedule?", "Каковы цена, валюта, налоги и график оплаты?", "Kāda ir cena, valūta, nodokļi un maksājumu grafiks?"), l("Offer options only if they are real; include validity period.", "Предлагайте варианты только если они реальны; укажите срок действия предложения.", "Piedāvājiet variantus tikai tad, ja tie ir reāli; norādiet derīguma termiņu.")),
    f("timeline", true, l("When can work start and finish?", "Когда работа может начаться и закончиться?", "Kad darbs var sākties un beigties?"), l("Milestones, dependencies, approval dates, and assumptions.", "Этапы, зависимости, даты согласований и предположения.", "Posmi, atkarības, apstiprinājumu datumi un pieņēmumi.")),
    f("nextStep", false, l("What should the client do next?", "Что клиент должен сделать дальше?", "Kas klientam jādara tālāk?"), l("Call, signature, reply, deposit, or decision deadline.", "Созвон, подпись, ответ, аванс или срок решения.", "Zvans, paraksts, atbilde, avanss vai lēmuma termiņš.")), extra,
  ]},
  sow: { intro: l("A statement of work should make scope, deliverables, milestones, acceptance, fees, dependencies, and change control measurable.", "Техническое задание должно измеримо описывать объём, результаты, этапы, приёмку, цену, зависимости и изменения.", "Darba uzdevumam izmērāmi jāapraksta apjoms, rezultāti, posmi, pieņemšana, cena, atkarības un izmaiņas."), fields: [party,
    f("objective", true, l("What project outcome is required?", "Какой результат проекта требуется?", "Kāds projekta rezultāts ir vajadzīgs?"), l("Define the business goal and success measure.", "Определите бизнес-цель и критерий успеха.", "Definējiet biznesa mērķi un veiksmes kritēriju.")),
    f("scope", true, l("What work is included and expressly excluded?", "Какие работы входят и прямо исключены?", "Kādi darbi ir iekļauti un skaidri izslēgti?"), l("Break the scope into workstreams or phases.", "Разбейте объём на направления или этапы.", "Sadaliet apjomu darba virzienos vai posmos."), true),
    f("deliverables", true, l("What deliverables, formats, and quality standards apply?", "Какие результаты, форматы и стандарты качества применяются?", "Kādi rezultāti, formāti un kvalitātes standarti jāpiemēro?"), l("Name each item, quantity, owner, and delivery method.", "Назовите каждый результат, объём, ответственного и способ передачи.", "Nosauciet katru rezultātu, apjomu, atbildīgo un nodošanas veidu."), true),
    f("milestones", true, l("What are the dates, milestones, and dependencies?", "Каковы даты, этапы и зависимости?", "Kādi ir datumi, posmi un atkarības?"), l("Include client inputs and review windows.", "Добавьте материалы заказчика и сроки проверки.", "Pievienojiet klienta materiālus un pārbaudes termiņus."), true),
    f("acceptance", true, l("How is each deliverable tested and accepted?", "Как каждый результат проверяется и принимается?", "Kā katrs rezultāts tiek pārbaudīts un pieņemts?"), l("Objective criteria, rejection notice, correction cycles, and sign-off.", "Объективные критерии, отказ, циклы исправлений и подтверждение.", "Objektīvi kritēriji, noraidījums, labojumu cikli un apstiprinājums."), true),
    f("fees", true, l("What are the fees, expenses, and payment triggers?", "Каковы цена, расходы и условия оплаты?", "Kādas ir maksas, izdevumi un maksājumu nosacījumi?"), l("Fixed price or time-based rates, caps, taxes, and invoice schedule.", "Фиксированная цена или ставки, пределы, налоги и график счетов.", "Fiksēta cena vai likmes, griesti, nodokļi un rēķinu grafiks.")),
    f("changes", false, l("How are scope changes requested, priced, and approved?", "Как запрашиваются, оцениваются и утверждаются изменения?", "Kā tiek pieprasītas, novērtētas un apstiprinātas izmaiņas?"), l("Require written change orders and identify authorized approvers.", "Предусмотрите письменные изменения и уполномоченных согласующих.", "Paredziet rakstiskus izmaiņu rīkojumus un pilnvarotus apstiprinātājus.")), extra,
  ]},
  minutes: { intro: l("Useful minutes distinguish discussion from decisions and assign every action to an owner and deadline.", "Хороший протокол отделяет обсуждение от решений и назначает каждому действию ответственного и срок.", "Labs protokols nošķir diskusiju no lēmumiem un katrai darbībai nosaka atbildīgo un termiņu."), fields: [
    f("meeting", true, l("What meeting was held, when, where, and why?", "Какое собрание прошло, когда, где и зачем?", "Kāda sanāksme notika, kad, kur un kāpēc?"), l("Title, date, start/end time, location or link, and chair.", "Название, дата, время, место или ссылка и председатель.", "Nosaukums, datums, laiks, vieta vai saite un vadītājs.")),
    f("attendees", true, l("Who attended, was absent, or joined as a guest?", "Кто присутствовал, отсутствовал или был приглашён?", "Kas piedalījās, nebija klāt vai bija viesis?"), l("Names, roles, represented organisations, and quorum if relevant.", "Имена, роли, организации и кворум, если применимо.", "Vārdi, lomas, pārstāvētās organizācijas un kvorums, ja vajag."), true),
    f("agenda", true, l("Which agenda items were discussed?", "Какие вопросы повестки обсуждались?", "Kādi darba kārtības jautājumi tika apspriesti?"), l("Keep the original order and add concise factual notes.", "Сохраните порядок и добавьте краткие фактические заметки.", "Saglabājiet secību un pievienojiet īsas faktiskas piezīmes."), true),
    f("decisions", true, l("What decisions or votes were made?", "Какие решения или голосования состоялись?", "Kādi lēmumi vai balsojumi notika?"), l("Exact decision, result, objections, and effective date.", "Точное решение, результат, возражения и дата вступления.", "Precīzs lēmums, rezultāts, iebildumi un spēkā stāšanās datums."), true),
    f("actions", true, l("What actions were assigned to whom and by when?", "Какие действия, кому и к какому сроку поручены?", "Kādas darbības, kam un līdz kuram datumam uzdotas?"), l("One action per line: owner, task, deadline, and status.", "Одно действие на строку: ответственный, задача, срок и статус.", "Viena darbība rindā: atbildīgais, uzdevums, termiņš un statuss."), true),
    f("nextMeeting", false, l("When is the next meeting or follow-up?", "Когда следующая встреча или проверка выполнения?", "Kad ir nākamā sanāksme vai izpildes pārbaude?"), l("Date, purpose, and preparation required.", "Дата, цель и необходимая подготовка.", "Datums, mērķis un vajadzīgā sagatavošanās.")), extra,
  ]},
  cv: { intro: l("A strong cover letter connects verified achievements to the exact role instead of repeating the CV.", "Сильное сопроводительное письмо связывает реальные достижения с конкретной вакансией, а не повторяет резюме.", "Spēcīga motivācijas vēstule sasaista pārbaudītus sasniegumus ar konkrēto amatu, nevis atkārto CV."), fields: [
    f("role", true, l("Which role and organisation are you applying to?", "На какую должность и в какую организацию вы подаётесь?", "Uz kādu amatu un kurā organizācijā piesakāties?"), l("Exact title, team, location, job link, and hiring manager if known.", "Точное название, команда, место, ссылка и имя менеджера, если известно.", "Precīzs nosaukums, komanda, vieta, saite un vadītājs, ja zināms.")),
    f("requirements", true, l("Which requirements from the vacancy matter most?", "Какие требования вакансии наиболее важны?", "Kuras vakances prasības ir svarīgākās?"), l("Paste 3–6 requirements you can genuinely address.", "Вставьте 3–6 требований, которым вы действительно соответствуете.", "Ievietojiet 3–6 prasības, kurām patiesi atbilstat."), true),
    f("experience", true, l("Which experience proves you can do this work?", "Какой опыт доказывает, что вы справитесь?", "Kāda pieredze pierāda, ka spēsiet veikt šo darbu?"), l("Role, responsibility, tools, scale, and context.", "Роль, ответственность, инструменты, масштаб и контекст.", "Loma, atbildība, rīki, mērogs un konteksts."), true),
    f("achievements", true, l("What measurable achievements should be highlighted?", "Какие измеримые достижения нужно выделить?", "Kādi izmērāmi sasniegumi jāizceļ?"), l("Use truthful numbers, outcomes, awards, or improvements.", "Используйте правдивые цифры, результаты, награды или улучшения.", "Izmantojiet patiesus skaitļus, rezultātus, balvas vai uzlabojumus."), true),
    f("motivation", true, l("Why this organisation and this role specifically?", "Почему именно эта организация и эта должность?", "Kāpēc tieši šī organizācija un šis amats?"), l("Mention a real product, mission, challenge, or team fit.", "Укажите реальный продукт, миссию, задачу или соответствие команде.", "Miniet īstu produktu, misiju, izaicinājumu vai atbilstību komandai."), true),
    f("tone", false, l("What tone, length, and contact details should be used?", "Какой тон, объём и контакты использовать?", "Kāds tonis, garums un kontakti jāizmanto?"), l("Concise or detailed; formal or warm; include only chosen contact details.", "Кратко или подробно; формально или тепло; добавьте только выбранные контакты.", "Īsi vai detalizēti; formāli vai silti; pievienojiet tikai izvēlētos kontaktus.")), extra,
  ]},
  birthday: { intro: l("A complete invitation needs the guest of honour, date, time, place, plan, guest instructions, and RSVP.", "Полное приглашение содержит именинника, дату, время, место, программу, инструкции гостям и RSVP.", "Pilnam ielūgumam vajag jubilāru, datumu, laiku, vietu, programmu, norādes viesiem un RSVP."), fields: [
    f("person", true, l("Whose birthday is it, and what age should be mentioned?", "Чей день рождения и нужно ли указывать возраст?", "Kam ir dzimšanas diena un vai jānorāda vecums?"), l("Name, age if desired, and host name.", "Имя, возраст при желании и имя организатора.", "Vārds, vecums pēc vēlēšanās un rīkotāja vārds.")),
    f("dateTime", true, l("What are the date, start time, and expected end time?", "Каковы дата, время начала и примерное окончание?", "Kāds ir datums, sākuma laiks un paredzamais beigu laiks?"), l("Include timezone for online or travelling guests.", "Для онлайн- или приезжих гостей укажите часовой пояс.", "Tiešsaistes vai ceļojošiem viesiem norādiet laika joslu.")),
    f("venue", true, l("Where will it take place?", "Где пройдёт праздник?", "Kur notiks svinības?"), l("Full address, room, access, parking, transport, or video link.", "Полный адрес, зал, вход, парковка, транспорт или видеоссылка.", "Pilna adrese, telpa, ieeja, stāvvieta, transports vai video saite.")),
    f("theme", false, l("What is the theme, programme, or dress guidance?", "Каковы тема, программа или дресс-код?", "Kāda ir tēma, programma vai apģērba norādes?"), l("Activities, food, surprises, dress code, and what guests should bring.", "Активности, еда, сюрпризы, одежда и что взять с собой.", "Aktivitātes, ēdiens, pārsteigumi, apģērbs un kas jāņem līdzi."), true),
    f("rsvp", true, l("How and by when should guests reply?", "Как и до какого срока гости должны ответить?", "Kā un līdz kuram datumam viesiem jāatbild?"), l("Contact person, phone or email, deadline, plus-one and dietary questions.", "Контакт, телефон или email, срок, сопровождающие и питание.", "Kontaktpersona, tālrunis vai e-pasts, termiņš, pavadoņi un ēdināšana.")), extra,
  ]},
  wedding: { intro: l("A wedding invitation should make the people, ceremony, reception, timing, guest rules, and RSVP unambiguous.", "Свадебное приглашение должно ясно сообщать имена, церемонию, банкет, время, правила для гостей и RSVP.", "Kāzu ielūgumam skaidri jānorāda cilvēki, ceremonija, svinības, laiks, viesu noteikumi un RSVP."), fields: [
    f("couple", true, l("What names should appear, and who is hosting?", "Какие имена указать и кто выступает организатором?", "Kādi vārdi jānorāda un kas rīko kāzas?"), l("Preferred spelling, surnames, parents or hosts if desired.", "Желаемое написание, фамилии, родители или организаторы при необходимости.", "Vēlamā rakstība, uzvārdi, vecāki vai rīkotāji, ja vajag.")),
    f("ceremony", true, l("When and where is the ceremony?", "Когда и где проходит церемония?", "Kad un kur notiek ceremonija?"), l("Date, arrival time, start time, venue, address, and access.", "Дата, время прибытия и начала, место, адрес и вход.", "Datums, ierašanās un sākuma laiks, vieta, adrese un piekļuve.")),
    f("reception", false, l("Is there a separate reception or programme?", "Будет ли отдельный банкет или программа?", "Vai būs atsevišķas svinības vai programma?"), l("Location, start/end, transport, accommodation, and key moments.", "Место, начало/конец, транспорт, проживание и основные моменты.", "Vieta, sākums/beigas, transports, naktsmītnes un galvenie brīži."), true),
    f("guestRules", false, l("What should guests know about dress, children, plus-ones, or gifts?", "Что гостям нужно знать об одежде, детях, сопровождающих или подарках?", "Kas viesiem jāzina par apģērbu, bērniem, pavadoņiem vai dāvanām?"), l("State sensitive rules warmly and clearly.", "Сформулируйте деликатные правила тепло и ясно.", "Formulējiet delikātus noteikumus silti un skaidri."), true),
    f("rsvp", true, l("How and by when should each guest reply?", "Как и до какого срока каждый гость должен ответить?", "Kā un līdz kuram datumam katram viesim jāatbild?"), l("Contact, deadline, attendance, plus-one, dietary and accommodation questions.", "Контакт, срок, участие, сопровождающие, питание и проживание.", "Kontakts, termiņš, dalība, pavadoņi, ēdināšana un naktsmītnes.")), extra,
  ]},
  event: { intro: l("An event invitation needs a clear value, audience, schedule, venue or link, practical instructions, and response path.", "Приглашение на мероприятие должно ясно сообщать ценность, аудиторию, программу, место, инструкции и способ ответа.", "Pasākuma ielūgumam skaidri jānorāda vērtība, auditorija, programma, vieta, norādes un atbildes veids."), fields: [
    f("event", true, l("What is the event and who is organising it?", "Что это за мероприятие и кто его организует?", "Kas tas ir par pasākumu un kas to rīko?"), l("Name, organiser, purpose, and one-sentence benefit for guests.", "Название, организатор, цель и польза для гостя одним предложением.", "Nosaukums, rīkotājs, mērķis un ieguvums viesim vienā teikumā.")),
    f("audience", true, l("Who is invited, and is attendance limited?", "Кто приглашён и ограничено ли количество мест?", "Kas ir aicināts un vai vietu skaits ir ierobežots?"), l("Public or private, age or role, capacity, and guest policy.", "Открытое или закрытое, возраст/роль, вместимость и сопровождающие.", "Publisks vai privāts, vecums/loma, ietilpība un pavadoņi.")),
    f("dateTime", true, l("What are the date, timezone, start, and end time?", "Каковы дата, часовой пояс, начало и конец?", "Kāds ir datums, laika josla, sākums un beigas?"), l("Include arrival, registration, and important session times.", "Добавьте время прибытия, регистрации и ключевых частей программы.", "Pievienojiet ierašanās, reģistrācijas un svarīgo sesiju laikus.")),
    f("venue", true, l("Where is it and how do guests join?", "Где это проходит и как гостям попасть?", "Kur tas notiek un kā viesi pievienojas?"), l("Address or link, room, entrance, accessibility, parking, transport.", "Адрес или ссылка, зал, вход, доступность, парковка, транспорт.", "Adrese vai saite, telpa, ieeja, pieejamība, stāvvieta, transports.")),
    f("programme", false, l("What will happen during the event?", "Что будет происходить на мероприятии?", "Kas notiks pasākumā?"), l("Agenda, speakers, activities, breaks, food, and what to bring.", "Программа, спикеры, активности, перерывы, еда и что взять.", "Programma, runātāji, aktivitātes, pauzes, ēdiens un kas jāņem."), true),
    f("registration", true, l("How and by when should people register or reply?", "Как и до какого срока зарегистрироваться или ответить?", "Kā un līdz kuram datumam jāreģistrējas vai jāatbild?"), l("Link or contact, deadline, fee, cancellation, and confirmation method.", "Ссылка или контакт, срок, цена, отмена и подтверждение.", "Saite vai kontakts, termiņš, maksa, atcelšana un apstiprinājums.")), extra,
  ]},
  thanks: { intro: l("A memorable thank-you letter names the contribution, its impact, and a sincere personal detail.", "Запоминающееся благодарственное письмо называет вклад, его эффект и искреннюю личную деталь.", "Atmiņā paliekoša pateicības vēstule nosauc ieguldījumu, tā ietekmi un patiesu personisku detaļu."), fields: [
    f("senderRecipient", true, l("Who is thanking whom, and what is the relationship?", "Кто кого благодарит и какие между ними отношения?", "Kas kam pateicas un kādas ir attiecības?"), l("Names, roles, organisation, and preferred form of address.", "Имена, роли, организация и предпочитаемое обращение.", "Vārdi, lomas, organizācija un vēlamā uzruna.")),
    f("reason", true, l("What exactly are you thanking them for?", "За что именно вы благодарите?", "Par ko tieši pateicaties?"), l("Name the action, support, gift, time, or opportunity.", "Назовите действие, помощь, подарок, время или возможность.", "Nosauciet darbību, palīdzību, dāvanu, laiku vai iespēju.")),
    f("impact", true, l("What difference did it make?", "Какой эффект это имело?", "Kādu ietekmi tas radīja?"), l("A concrete result, feeling, lesson, or benefit.", "Конкретный результат, чувство, урок или польза.", "Konkrēts rezultāts, sajūta, mācība vai ieguvums.")),
    f("detail", false, l("Which personal detail or moment should be mentioned?", "Какую личную деталь или момент стоит упомянуть?", "Kāda personiska detaļa vai brīdis jāpiemin?"), l("One genuine memory makes the message specific.", "Одно настоящее воспоминание сделает письмо личным.", "Viena īsta atmiņa padarīs vēstuli personisku.")),
    f("tone", false, l("Should it be formal, warm, concise, or emotional?", "Письмо должно быть формальным, тёплым, кратким или эмоциональным?", "Vai vēstulei jābūt formālai, siltai, īsai vai emocionālai?"), l("Also state the sender name and sign-off.", "Также укажите имя отправителя и подпись.", "Norādiet arī sūtītāja vārdu un parakstu.")), extra,
  ]},
  custom: { intro: l("Describe the document from first principles. These questions prevent the AI from guessing the purpose, parties, facts, obligations, or legal context.", "Опишите документ с нуля. Эти вопросы не дадут ИИ додумать цель, стороны, факты, обязанности или правовой контекст.", "Aprakstiet dokumentu no pamatiem. Šie jautājumi neļaus AI izdomāt mērķi, puses, faktus, pienākumus vai tiesisko kontekstu."), fields: [
    f("documentType", true, l("What exact document do you need?", "Какой именно документ вам нужен?", "Kāds tieši dokuments jums vajadzīgs?"), l("Name it if you know; otherwise describe its function and where it will be used.", "Назовите тип, если знаете; иначе опишите функцию и где он будет использоваться.", "Nosauciet tipu, ja zināt; citādi aprakstiet funkciju un lietošanas vietu.")),
    f("purpose", true, l("What real-world outcome must the document achieve?", "Какой практический результат должен дать документ?", "Kāds praktisks rezultāts dokumentam jāsasniedz?"), l("What should happen after someone reads, signs, or receives it?", "Что должно произойти после прочтения, подписания или получения?", "Kam jānotiek pēc izlasīšanas, parakstīšanas vai saņemšanas?"), true),
    party,
    f("audience", true, l("Who will read, sign, approve, or rely on it?", "Кто будет читать, подписывать, утверждать или использовать документ?", "Kas dokumentu lasīs, parakstīs, apstiprinās vai uz to paļausies?"), l("Private person, company, authority, court, bank, school, employer, or public audience.", "Частное лицо, компания, ведомство, суд, банк, школа, работодатель или публика.", "Privātpersona, uzņēmums, iestāde, tiesa, banka, skola, darba devējs vai sabiedrība.")),
    f("facts", true, l("Which facts must be treated as certain?", "Какие факты нужно считать подтверждёнными?", "Kādi fakti jāuzskata par drošiem?"), l("Names, dates, amounts, addresses, identifiers, prior events, and evidence.", "Имена, даты, суммы, адреса, номера, прежние события и доказательства.", "Vārdi, datumi, summas, adreses, identifikatori, iepriekšējie notikumi un pierādījumi."), true),
    f("obligations", true, l("What must each person do, not do, give, pay, or deliver?", "Что каждая сторона должна сделать, не делать, передать, оплатить или предоставить?", "Kas katrai pusei jādara, nav jādara, jānodod, jāmaksā vai jāpiegādā?"), l("Include quantities, standards, deadlines, dependencies, and acceptance.", "Добавьте объём, стандарты, сроки, зависимости и приёмку.", "Pievienojiet apjomu, standartus, termiņus, atkarības un pieņemšanu."), true),
    f("datesMoney", false, l("Which dates, time periods, amounts, currencies, or payment rules apply?", "Какие даты, периоды, суммы, валюты или правила оплаты применяются?", "Kādi datumi, periodi, summas, valūtas vai maksājumu noteikumi jāpiemēro?"), l("Do not leave monetary or deadline terms implicit.", "Не оставляйте денежные условия и сроки подразумеваемыми.", "Neatstājiet naudas noteikumus un termiņus netiešus."), true),
    f("risks", false, l("What could go wrong, and what should happen then?", "Что может пойти не так и что тогда должно произойти?", "Kas var noiet greizi un kam tad jānotiek?"), l("Delay, cancellation, breach, error, damage, dispute, refund, or force majeure.", "Задержка, отмена, нарушение, ошибка, ущерб, спор, возврат или форс-мажор.", "Kavējums, atcelšana, pārkāpums, kļūda, kaitējums, strīds, atmaksa vai nepārvarama vara."), true),
    f("formatTone", false, l("What format, tone, length, and delivery method do you need?", "Каковы формат, тон, объём и способ передачи?", "Kāds formāts, tonis, garums un piegādes veids vajadzīgs?"), l("Formal letter, agreement, policy, notice, email, checklist; concise or detailed.", "Письмо, договор, политика, уведомление, email, чек-лист; кратко или подробно.", "Vēstule, līgums, politika, paziņojums, e-pasts, kontrolsaraksts; īsi vai detalizēti.")),
    law, extra,
  ]},
};

export function guideFor(templateId: string): StudioTemplateGuide {
  return studioTemplateGuides[templateId] ?? studioTemplateGuides.custom;
}

export function guideText(value: Localized, locale: StudioGuideLocale): string {
  return value[locale] ?? value.en;
}

export function requiredRegionFor(country: string): boolean {
  return ["United States", "Canada", "Germany", "Brazil", "Australia", "Switzerland"].includes(country);
}
