"use client";

import { useEffect, useMemo, useState } from "react";
import { studioCountries, type GeneratedDocument, type StudioMode } from "./document-studio-schema";
import type { ProfileLanguage } from "./profile-types";
import { getAccessToken, type SupabaseAccount } from "./supabase-auth";

type Readiness="green"|"yellow"|"red";
type Saved={id:string;createdAt:number;result:GeneratedDocument};
const text={
  en:{live:"Secure AI workspace",title:"Create & edit documents",subtitle:"Choose a template, add the facts, and get a private editable draft.",create:"Create new",improve:"Improve existing",review:"Review & check",templates:"Choose a starting point",details:"Add the details",country:"Country or legal jurisdiction",countryHint:"Required. Laws and official requirements vary by location.",region:"Region / state (if relevant)",language:"Document language",goal:"What should the document achieve?",existing:"Paste the existing document",landlord:"Landlord / owner",tenant:"Tenant",property:"Property address",rent:"Monthly rent",start:"Start date",end:"End date",notes:"Special terms",readiness:"AI readiness",green:"Ready to create",yellow:"More detail would improve the result",red:"Critical information is missing",missing:"Missing",generate:"Generate private draft",generating:"Generating…",signin:"Sign in to create and save documents",warning:"Before we continue",warningBody:"Important details are missing. Continue only if you accept explicit placeholders and assumptions.",add:"Add information",continue:"Continue as is",back:"Back to details",draft:"Generated document",copy:"Copy",docx:"DOCX",pdf:"PDF",history:"Recent documents",historyButton:"Document history",empty:"Your latest 10 generated documents will appear here.",limit:"Usage",delete:"Delete",sources:"Official sources consulted",issues:"Check before use",error:"The document could not be generated. Try again.",disclaimer:"AI-generated draft for informational purposes only. It is not professional advice and is not guaranteed to be complete, legally valid, enforceable, or suitable for your situation. Check all facts and applicable rules before use. For important matters, consult a qualified professional or authority.",lease:"Residential lease",service:"Service agreement",nda:"Non-disclosure agreement",loan:"Loan agreement",power:"Power of attorney",complaint:"Formal complaint",request:"Official request",termination:"Termination notice",letter:"Formal letter",proposal:"Commercial proposal",sow:"Statement of work",minutes:"Meeting minutes",cv:"Cover letter",birthday:"Birthday invitation",wedding:"Wedding invitation",event:"Event invitation",thanks:"Thank-you letter",custom:"Custom document"},
  ru:{live:"Защищённая AI-мастерская",title:"Создание и редактирование",subtitle:"Выберите шаблон, добавьте факты и получите приватный редактируемый черновик.",create:"Создать новый",improve:"Улучшить готовый",review:"Проверить документ",templates:"Выберите основу",details:"Добавьте данные",country:"Страна или юрисдикция",countryHint:"Обязательное поле. Законы и требования зависят от места.",region:"Регион / штат (если нужно)",language:"Язык документа",goal:"Какую задачу должен решить документ?",existing:"Вставьте готовый документ",landlord:"Арендодатель / владелец",tenant:"Арендатор",property:"Адрес недвижимости",rent:"Арендная плата",start:"Дата начала",end:"Дата окончания",notes:"Особые условия",readiness:"Готовность ИИ",green:"Можно создавать",yellow:"Больше деталей улучшат результат",red:"Критически мало информации",missing:"Не хватает",generate:"Создать приватный черновик",generating:"Создаём…",signin:"Войдите, чтобы создавать и сохранять документы",warning:"Перед продолжением",warningBody:"Важных данных не хватает. Продолжайте, только если согласны с явными заполнителями и предположениями.",add:"Добавить данные",continue:"Всё равно продолжить",back:"Вернуться к данным",draft:"Готовый документ",copy:"Копировать",docx:"DOCX",pdf:"PDF",history:"Последние документы",historyButton:"История документов",empty:"Здесь будут храниться последние 10 созданных документов.",limit:"Лимит",delete:"Удалить",sources:"Проверенные официальные источники",issues:"Проверить перед использованием",error:"Не удалось создать документ. Попробуйте снова.",disclaimer:"Черновик создан ИИ только в информационных целях. Это не профессиональная консультация; полнота, юридическая сила и пригодность не гарантируются. Проверьте все факты и применимые правила. В важных случаях обратитесь к специалисту или органу власти.",lease:"Договор аренды жилья",service:"Договор услуг",nda:"Соглашение о конфиденциальности",loan:"Договор займа",power:"Доверенность",complaint:"Официальная жалоба",request:"Официальное заявление",termination:"Уведомление о расторжении",letter:"Деловое письмо",proposal:"Коммерческое предложение",sow:"Техническое задание",minutes:"Протокол встречи",cv:"Сопроводительное письмо",birthday:"Приглашение на день рождения",wedding:"Приглашение на свадьбу",event:"Приглашение на мероприятие",thanks:"Благодарственное письмо",custom:"Свой документ"},
  lv:{live:"Droša AI darbnīca",title:"Izveidot un rediģēt dokumentus",subtitle:"Izvēlieties veidni, pievienojiet faktus un saņemiet privātu, rediģējamu melnrakstu.",create:"Izveidot jaunu",improve:"Uzlabot esošo",review:"Pārskatīt dokumentu",templates:"Izvēlieties sākumpunktu",details:"Pievienojiet informāciju",country:"Valsts vai jurisdikcija",countryHint:"Obligāti. Likumi un prasības atšķiras.",region:"Reģions / štats",language:"Dokumenta valoda",goal:"Kāds ir dokumenta mērķis?",existing:"Ielīmējiet esošo dokumentu",landlord:"Iznomātājs",tenant:"Īrnieks",property:"Īpašuma adrese",rent:"Īres maksa",start:"Sākuma datums",end:"Beigu datums",notes:"Īpašie noteikumi",readiness:"AI gatavība",green:"Gatavs izveidei",yellow:"Papildu informācija uzlabos rezultātu",red:"Trūkst būtiskas informācijas",missing:"Trūkst",generate:"Izveidot privātu melnrakstu",generating:"Izveidojam…",signin:"Pierakstieties, lai izveidotu un saglabātu dokumentus",warning:"Pirms turpināt",warningBody:"Trūkst svarīgas informācijas. Turpiniet tikai tad, ja piekrītat vietturiem un pieņēmumiem.",add:"Pievienot datus",continue:"Tomēr turpināt",back:"Atpakaļ pie datiem",draft:"Izveidotais dokuments",copy:"Kopēt",docx:"DOCX",pdf:"PDF",history:"Jaunākie dokumenti",historyButton:"Dokumentu vēsture",empty:"Šeit tiks glabāti pēdējie 10 izveidotie dokumenti.",limit:"Limits",delete:"Dzēst",sources:"Izmantotie oficiālie avoti",issues:"Pārbaudīt pirms lietošanas",error:"Dokumentu neizdevās izveidot. Mēģiniet vēlreiz.",disclaimer:"AI melnraksts ir tikai informatīvs. Tā nav profesionāla konsultācija, un netiek garantēta pilnība, juridiskais spēks vai piemērotība. Pārbaudiet faktus un noteikumus. Svarīgos jautājumos konsultējieties ar speciālistu vai iestādi.",lease:"Dzīvojamās telpas īres līgums",service:"Pakalpojumu līgums",nda:"Konfidencialitātes līgums",loan:"Aizdevuma līgums",power:"Pilnvara",complaint:"Oficiāla sūdzība",request:"Oficiāls iesniegums",termination:"Uzteikuma paziņojums",letter:"Oficiāla vēstule",proposal:"Komerciāls piedāvājums",sow:"Darba uzdevums",minutes:"Sanāksmes protokols",cv:"Motivācijas vēstule",birthday:"Dzimšanas dienas ielūgums",wedding:"Kāzu ielūgums",event:"Pasākuma ielūgums",thanks:"Pateicības vēstule",custom:"Cits dokuments"}
} as const;
type Copy=(typeof text)["en"];
const fileText={
  en:{upload:"Or attach the existing document",chooseFile:"Choose document",removeFile:"Remove",fileHint:"PDF, image, TXT, RTF, DOCX, or ODT. Maximum size depends on format."},
  ru:{upload:"Или прикрепите готовый документ",chooseFile:"Выбрать документ",removeFile:"Удалить",fileHint:"PDF, изображение, TXT, RTF, DOCX или ODT. Максимальный размер зависит от формата."},
  lv:{upload:"Vai pievienojiet esošo dokumentu",chooseFile:"Izvēlēties dokumentu",removeFile:"Noņemt",fileHint:"PDF, attēls, TXT, RTF, DOCX vai ODT. Maksimālais izmērs ir atkarīgs no formāta."},
} as const;
type StudioCopy=Copy&(typeof fileText)["en"];
const reasoningText={en:{reasoningTime:"Reasoning time",reasoningEstimate:"Usually about 2–3 minutes"},ru:{reasoningTime:"Время рассуждения",reasoningEstimate:"Обычно около 2–3 минут"},lv:{reasoningTime:"Spriešanas laiks",reasoningEstimate:"Parasti aptuveni 2–3 minūtes"}} as const;
type StudioReasoningCopy=(typeof reasoningText)["en"];
function formatDuration(totalSeconds:number){const minutes=Math.floor(totalSeconds/60).toString().padStart(2,"0"),seconds=(totalSeconds%60).toString().padStart(2,"0");return `${minutes}:${seconds}`}
const templates=[["lease","legal","⌂"],["service","work","↗"],["nda","legal","◎"],["loan","legal","€"],["power","legal","◇"],["complaint","legal","!"],["request","legal","→"],["termination","work","×"],["letter","work","Aa"],["proposal","work","%"],["sow","work","✓"],["minutes","work","≡"],["cv","work","✦"],["birthday","events","○"],["wedding","events","∞"],["event","events","◌"],["thanks","personal","♡"],["custom","personal","+"]] as const;
const languages=[{code:"en",name:"English"},{code:"ru",name:"Русский"},{code:"lv",name:"Latviešu"},{code:"de",name:"Deutsch"},{code:"fr",name:"Français"},{code:"es",name:"Español"},{code:"pt",name:"Português"},{code:"it",name:"Italiano"},{code:"pl",name:"Polski"},{code:"uk",name:"Українська"},{code:"nl",name:"Nederlands"},{code:"ro",name:"Română"},{code:"sv",name:"Svenska"},{code:"cs",name:"Čeština"}] as const;

export function DocumentStudioPrototype({locale,account,onRequireAccount}:{locale:ProfileLanguage;account:SupabaseAccount|null;onRequireAccount:()=>void}){
  const copyLocale=locale==="ru"||locale==="lv"?locale:"en",t=({...text[copyLocale],...fileText[copyLocale],...reasoningText[copyLocale]} as StudioCopy&StudioReasoningCopy),[mode,setMode]=useState<StudioMode>("create"),[template,setTemplate]=useState("lease"),[country,setCountry]=useState("Latvia"),[region,setRegion]=useState(""),[language,setLanguage]=useState(locale==="ru"?"ru":locale==="lv"?"lv":"en"),[fields,setFields]=useState({landlord:"",tenant:"",property:"",rent:"",start:"",end:"",notes:"",goal:"",existing:""}),[sourceFile,setSourceFile]=useState<File|null>(null),[warning,setWarning]=useState(false),[busy,setBusy]=useState(false),[elapsed,setElapsed]=useState(0),[error,setError]=useState(""),[current,setCurrent]=useState<Saved|null>(null),[history,setHistory]=useState<Saved[]>([]),[quota,setQuota]=useState<{remaining:number;dailyUsed:number;dailyLimit:number;monthlyUsed:number;monthlyLimit:number}|null>(null);
  const missing=useMemo(()=>mode!=="create"?[!(fields.existing||sourceFile)?"existing_document":"",!fields.goal?"requested_changes":""].filter(Boolean):template==="lease"?[!(fields.landlord&&fields.tenant)?"parties":"",!fields.property?"property_address":"",!fields.start?"start_date":"",!fields.rent?"rent_amount":"",!fields.end?"end_date":"",!fields.notes?"deposit_utilities_and_notice_terms":""].filter(Boolean):[(fields.goal.trim().length<20)?"purpose_and_key_facts":fields.goal.trim().length<80?"more_specific_details":""].filter(Boolean),[mode,template,fields,sourceFile]);
  const readiness:Readiness=missing.length>=3?"red":missing.length?"yellow":"green";
  const load=async()=>{if(!account)return;const token=await getAccessToken();if(!token)return;const r=await fetch("/api/document-studio",{headers:{Authorization:`Bearer ${token}`}});if(r.ok){const d=await r.json() as {documents:Saved[];quota:typeof quota};setHistory(d.documents);setQuota(d.quota)}};
  useEffect(()=>{void load()},[account]);
  useEffect(()=>{if(!busy){setElapsed(0);return}const started=Date.now(),timer=window.setInterval(()=>setElapsed(Math.min(180,Math.floor((Date.now()-started)/1000))),1000);return()=>window.clearInterval(timer)},[busy]);
  const update=(key:keyof typeof fields,value:string)=>{setFields(x=>({...x,[key]:value}));setCurrent(null);setError("")};
  const generate=async(confirmed=false)=>{if(!account){onRequireAccount();return}if(readiness!=="green"&&!confirmed){setWarning(true);return}setBusy(true);setError("");try{const token=await getAccessToken();if(!token)throw new Error();const requestData={mode,templateId:template,country,region,outputLanguage:language,details:fields,confirmedInsufficient:confirmed};const body=sourceFile?(()=>{const form=new FormData();form.append("request",JSON.stringify(requestData));form.append("file",sourceFile);return form})():JSON.stringify(requestData);const r=await fetch("/api/document-studio",{method:"POST",headers:{Authorization:`Bearer ${token}`,...(!sourceFile?{"Content-Type":"application/json"}:{})},body});const d=await r.json() as {document?:Saved;quota?:typeof quota;error?:{message?:string}};if(!r.ok||!d.document)throw new Error(d.error?.message);setCurrent(d.document);setQuota(d.quota??null);setHistory(x=>[d.document!,...x].slice(0,10))}catch(e){setError(e instanceof Error&&e.message?e.message:t.error)}finally{setBusy(false)}};
  const download=async(format:"docx"|"pdf")=>{if(!current)return;if(format==="pdf"){const escape=(value:string)=>value.replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");const safe=escape(current.result.plainText),title=escape(current.result.title);const blob=new Blob([`<!doctype html><meta charset="utf-8"><title>${title}</title><style>body{font:12pt/1.55 system-ui;max-width:760px;margin:40px auto;white-space:pre-wrap}@media print{body{margin:0}}</style><body>${safe}<script>onload=()=>print()<\/script>`],{type:"text/html"});const url=URL.createObjectURL(blob);window.open(url,"_blank","noopener,noreferrer");setTimeout(()=>URL.revokeObjectURL(url),60_000);return}const token=await getAccessToken();if(!token)return;const r=await fetch(`/api/document-studio/export?id=${encodeURIComponent(current.id)}&format=${format}`,{headers:{Authorization:`Bearer ${token}`}});if(!r.ok){setError(t.error);return}const blob=await r.blob(),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`${current.result.title}.${format}`;a.click();URL.revokeObjectURL(url)};
  const remove=async(id:string)=>{const token=await getAccessToken();if(!token)return;const r=await fetch(`/api/document-studio?id=${encodeURIComponent(id)}`,{method:"DELETE",headers:{Authorization:`Bearer ${token}`}});if(r.ok){setHistory(x=>x.filter(d=>d.id!==id));if(current?.id===id)setCurrent(null)}};
  if(current)return <StudioDraft t={t} item={current} onBack={()=>setCurrent(null)} onCopy={()=>navigator.clipboard.writeText(current.result.plainText)} onDownload={download}/>;
  return <section className="studio-shell" aria-labelledby="studio-title"><div className="studio-heading"><div><div className="studio-heading-labels"><span className="studio-prototype-pill">{t.live}</span><span className="studio-beta-badge" title="Beta testing — some features may still change">Beta</span></div><h1 id="studio-title">{t.title}</h1><p>{t.subtitle}</p></div><div className="studio-heading-actions">{account&&<button className="studio-history-toggle" type="button" onClick={()=>document.getElementById("studio-history")?.scrollIntoView({behavior:"smooth",block:"start"})}>{t.historyButton}</button>}<div className={`readiness-orb ${readiness}`}><span>{readiness==="green"?"✓":readiness==="yellow"?"~":"!"}</span></div></div></div>
    <div className="studio-action-switch" role="tablist">{(["create","improve","review"] as StudioMode[]).map(x=><button key={x} type="button" role="tab" aria-selected={mode===x} className={mode===x?"active":""} onClick={()=>{setMode(x);if(x==="create")setSourceFile(null)}}>{t[x]}</button>)}</div>
    <div className="studio-workspace"><aside className="template-library"><div className="template-library-heading"><h2>{t.templates}</h2></div><div className="template-grid">{templates.map(([key,,icon])=><button type="button" className={template===key?"active":""} key={key} onClick={()=>setTemplate(key)}><span>{icon}</span><strong>{t[key as keyof Copy]}</strong></button>)}</div>{account&&<div className="studio-history" id="studio-history"><h3>{t.history}</h3>{quota&&<p>{t.limit}: {quota.remaining} · 24h {quota.dailyUsed}/{quota.dailyLimit} · 30d {quota.monthlyUsed}/{quota.monthlyLimit}</p>}{history.length?history.map(x=><div key={x.id}><button type="button" onClick={()=>setCurrent(x)}>{x.result.title}</button><button type="button" aria-label={t.delete} onClick={()=>void remove(x.id)}>×</button></div>):<p>{t.empty}</p>}</div>}</aside>
      <div className="studio-form-panel"><div className="studio-form-title"><span className="studio-step">2</span><div><h2>{t.details}</h2><p>{t[template as keyof Copy]}</p></div></div><div className="studio-form-grid"><label className="span-2"><span>{t.country}</span><select value={country} onChange={e=>setCountry(e.target.value)}>{studioCountries.map(x=><option key={x}>{x}</option>)}</select><small>{t.countryHint}</small></label><label><span>{t.region}</span><input value={region} onChange={e=>setRegion(e.target.value)}/></label><label><span>{t.language}</span><select value={language} onChange={e=>setLanguage(e.target.value)}>{languages.map(x=><option key={x.code} value={x.code}>{x.name}</option>)}</select></label>
      {mode==="create"&&template==="lease"?<><label><span>{t.landlord}</span><input value={fields.landlord} onChange={e=>update("landlord",e.target.value)}/></label><label><span>{t.tenant}</span><input value={fields.tenant} onChange={e=>update("tenant",e.target.value)}/></label><label className="span-2"><span>{t.property}</span><input value={fields.property} onChange={e=>update("property",e.target.value)}/></label><label><span>{t.rent}</span><input value={fields.rent} onChange={e=>update("rent",e.target.value)}/></label><label><span>{t.start}</span><input type="date" value={fields.start} onChange={e=>update("start",e.target.value)}/></label><label><span>{t.end}</span><input type="date" value={fields.end} onChange={e=>update("end",e.target.value)}/></label><label className="span-2"><span>{t.notes}</span><textarea rows={4} value={fields.notes} onChange={e=>update("notes",e.target.value)}/></label></>:mode==="create"?<label className="span-2"><span>{t.goal}</span><textarea rows={9} value={fields.goal} onChange={e=>update("goal",e.target.value)}/></label>:<><label className="span-2"><span>{t.goal}</span><textarea rows={4} value={fields.goal} onChange={e=>update("goal",e.target.value)}/></label><label className="span-2"><span>{t.existing}</span><textarea rows={14} value={fields.existing} onChange={e=>update("existing",e.target.value)}/></label></>}</div>{mode!=="create"&&<StudioFileField t={t} file={sourceFile} onFile={file=>{setSourceFile(file);setError("")}}/>}
      <div className={`studio-readiness ${readiness}`}><div className="studio-readiness-meter"><span style={{width:readiness==="green"?"100%":readiness==="yellow"?"62%":"28%"}}/></div><div><small>{t.readiness}</small><strong>{t[readiness]}</strong>{missing.length>0&&<p>{t.missing}: {missing.join(", ")}</p>}</div></div>{error&&<p className="studio-api-error" role="alert">{error}</p>}<button className="primary-button studio-generate" disabled={busy||quota?.remaining===0} type="button" onClick={()=>void generate()}>{busy?t.generating:account?t.generate:t.signin}<span>→</span></button>{busy&&<p className="studio-generation-timer" role="status" aria-live="polite"><span>{t.reasoningTime}: {formatDuration(elapsed)} / 03:00</span><small>{t.reasoningEstimate}</small></p>}</div></div>
    <div className="studio-legal-note"><span>i</span><p>{t.disclaimer}</p></div>{warning&&<div className="studio-warning-backdrop"><section className="studio-warning" role="dialog" aria-modal="true"><div className={`readiness-orb ${readiness}`}><span>!</span></div><h2>{t.warning}</h2><p>{t.warningBody}</p><div className="studio-warning-actions"><button type="button" onClick={()=>setWarning(false)}>{t.add}</button><button className="primary-button" type="button" onClick={()=>{setWarning(false);void generate(true)}}>{t.continue}</button></div></section></div>}</section>
}

function StudioFileField({t,file,onFile}:{t:StudioCopy;file:File|null;onFile:(file:File|null)=>void}){return <div className="studio-file-field"><span>{t.upload}</span><input key={file?`${file.name}-${file.lastModified}`:"empty"} id="studio-document-file" className="visually-hidden" type="file" accept=".pdf,.jpg,.jpeg,.png,.webp,.txt,.rtf,.docx,.odt" onChange={event=>onFile(event.target.files?.[0]??null)}/><label htmlFor="studio-document-file" className="studio-file-button">{t.chooseFile}</label>{file&&<div className="studio-selected-file"><strong title={file.name}>{file.name}</strong><span>{Math.max(1,Math.round(file.size/1024))} KB</span><button type="button" onClick={()=>onFile(null)}>{t.removeFile}</button></div>}<small>{t.fileHint}</small></div>}

function StudioDraft({t,item,onBack,onCopy,onDownload}:{t:Copy;item:Saved;onBack:()=>void;onCopy:()=>void;onDownload:(f:"docx"|"pdf")=>void}){const d=item.result;return <div className="studio-draft-layout"><aside><button type="button" onClick={onBack}>← {t.back}</button><div><small>{t.issues}</small><ul>{[...d.assumptions,...d.unresolvedIssues.map(x=>x.issue)].map((x,i)=><li key={i}>{x}</li>)}</ul></div>{d.legalSources.length>0&&<div><small>{t.sources}</small><ul>{d.legalSources.map((x,i)=><li key={i}><a href={x.url} target="_blank" rel="noreferrer">{x.title}</a></li>)}</ul></div>}</aside><article className="studio-document-paper"><div className="studio-document-toolbar"><strong>{t.draft}</strong><div><button type="button" onClick={onCopy}>{t.copy}</button><button type="button" onClick={()=>onDownload("docx")}>{t.docx}</button><button type="button" onClick={()=>onDownload("pdf")}>{t.pdf}</button></div></div><div contentEditable suppressContentEditableWarning><p className="document-kicker">{d.country}{d.region?` · ${d.region}`:""}</p><h2>{d.title}</h2>{d.sections.map((s,i)=><section key={i}><h3>{s.heading}</h3>{s.body.split("\n").map((p,j)=><p key={j}>{p}</p>)}</section>)}</div></article></div>}
