import type { SupportedLanguage } from "./analysis-schema";

export const reminderCopy = {
  ru: {
    eyebrow: "Email-напоминания", title: "Не пропустите важную дату",
    intro: "WhatNow? может один раз запомнить ваше согласие и отправлять напоминания на подтверждённую почту аккаунта.",
    consentTitle: "Разрешить email-напоминания", consentText: "Я разрешаю WhatNow? отправлять только напоминания о датах из моих сохранённых разборов. Разрешение можно отозвать в профиле.",
    consentCheckbox: "Я согласен получать такие email-напоминания", enable: "Включить напоминания", enabling: "Сохраняем согласие…",
    timezone: "Часовой пояс", timezoneHelp: "По умолчанию используется Europe/Riga. Его можно изменить в профиле.",
    savingAnalysis: "Сначала завершаем безопасное сохранение разбора в аккаунт…", noEvents: "В документе не найдено точных будущих дат, для которых можно создать напоминание.",
    date: "Дата", dateMissing: "Точная дата не найдена — проверьте документ и укажите её вручную.", time: "Время", timeMissing: "В документе нет точного времени — укажите его вручную.", eventTimezone: "Часовой пояс события",
    remindWhen: "Когда напомнить", hour: "За 1 час", day: "За 24 часа", week: "За 1 неделю", month: "За 30 дней",
    defaultNote: "Если ничего не менять, для точной даты и времени автоматически выбирается вариант за 24 часа.",
    schedule: "Сохранить напоминание", scheduling: "Сохраняем…", replace: "Изменить напоминание", cancel: "Отменить", cancelling: "Отменяем…",
    scheduled: "Напоминание запланировано", sent: "Напоминание отправлено", failed: "Отправка не удалась", sending: "Напоминание отправляется",
    willSend: "Письмо будет отправлено", noAvailableOffsets: "До события осталось слишком мало времени для этих вариантов.",
    autoScheduled: "Автоматически создано напоминание за 24 часа.", saved: "Напоминание сохранено.", cancelled: "Напоминание отменено.",
    loadError: "Не удалось загрузить напоминания. Попробуйте позже.", actionError: "Не удалось сохранить напоминание. Проверьте дату и время.",
    pilot: "Напоминания пока проходят закрытое тестирование.", unavailable: "Сервис напоминаний пока не настроен.",
    sourceLanguage: "Язык письма совпадает с языком исходного документа.", verify: "Проверьте дату и время по исходному документу.",
    profileTitle: "Email-напоминания", profileIntro: "Управляйте согласием, часовым поясом и будущими письмами.", enabled: "Разрешены", disabled: "Выключены",
    disable: "Отключить и отменить будущие", saveTimezone: "Сохранить часовой пояс", settingsSaved: "Настройки сохранены.", upcoming: "Будущие напоминания", noneUpcoming: "Запланированных напоминаний пока нет.",
  },
  lv: {
    eyebrow: "E-pasta atgādinājumi", title: "Nepalaidiet garām svarīgu datumu",
    intro: "WhatNow? var vienreiz saglabāt jūsu piekrišanu un sūtīt atgādinājumus uz konta apstiprināto e-pastu.",
    consentTitle: "Atļaut e-pasta atgādinājumus", consentText: "Es atļauju WhatNow? sūtīt tikai atgādinājumus par datumiem manos saglabātajos pārskatos. Atļauju var atsaukt profilā.",
    consentCheckbox: "Piekrītu saņemt šādus e-pasta atgādinājumus", enable: "Ieslēgt atgādinājumus", enabling: "Saglabājam piekrišanu…",
    timezone: "Laika josla", timezoneHelp: "Pēc noklusējuma tiek izmantota Europe/Riga. To var mainīt profilā.",
    savingAnalysis: "Vispirms pabeidzam drošu analīzes saglabāšanu kontā…", noEvents: "Dokumentā nav atrasti precīzi nākotnes datumi, kuriem var izveidot atgādinājumu.",
    date: "Datums", dateMissing: "Precīzs datums nav atrasts — pārbaudiet dokumentu un ievadiet to manuāli.", time: "Laiks", timeMissing: "Dokumentā nav precīza laika — ievadiet to manuāli.", eventTimezone: "Notikuma laika josla",
    remindWhen: "Kad atgādināt", hour: "1 stundu iepriekš", day: "24 stundas iepriekš", week: "1 nedēļu iepriekš", month: "30 dienas iepriekš",
    defaultNote: "Ja neko nemaināt, precīzam datumam un laikam automātiski tiek izvēlētas 24 stundas iepriekš.",
    schedule: "Saglabāt atgādinājumu", scheduling: "Saglabājam…", replace: "Mainīt atgādinājumu", cancel: "Atcelt", cancelling: "Atceļam…",
    scheduled: "Atgādinājums ieplānots", sent: "Atgādinājums nosūtīts", failed: "Nosūtīšana neizdevās", sending: "Atgādinājums tiek sūtīts",
    willSend: "E-pasts tiks nosūtīts", noAvailableOffsets: "Līdz notikumam ir par maz laika šīm izvēlēm.",
    autoScheduled: "Automātiski izveidots atgādinājums 24 stundas iepriekš.", saved: "Atgādinājums saglabāts.", cancelled: "Atgādinājums atcelts.",
    loadError: "Neizdevās ielādēt atgādinājumus. Mēģiniet vēlāk.", actionError: "Neizdevās saglabāt atgādinājumu. Pārbaudiet datumu un laiku.",
    pilot: "Atgādinājumi pašlaik tiek testēti slēgtā režīmā.", unavailable: "Atgādinājumu pakalpojums vēl nav iestatīts.",
    sourceLanguage: "E-pasta valoda atbilst sākotnējā dokumenta valodai.", verify: "Pārbaudiet datumu un laiku sākotnējā dokumentā.",
    profileTitle: "E-pasta atgādinājumi", profileIntro: "Pārvaldiet piekrišanu, laika joslu un gaidāmos e-pastus.", enabled: "Atļauti", disabled: "Izslēgti",
    disable: "Izslēgt un atcelt nākamos", saveTimezone: "Saglabāt laika joslu", settingsSaved: "Iestatījumi saglabāti.", upcoming: "Gaidāmie atgādinājumi", noneUpcoming: "Ieplānotu atgādinājumu vēl nav.",
  },
  en: {
    eyebrow: "Email reminders", title: "Do not miss an important date",
    intro: "WhatNow? can remember your consent once and send reminders to the verified email on your account.",
    consentTitle: "Allow email reminders", consentText: "I allow WhatNow? to send only reminders about dates in my saved analyses. I can withdraw permission in my profile.",
    consentCheckbox: "I agree to receive these email reminders", enable: "Enable reminders", enabling: "Saving consent…",
    timezone: "Time zone", timezoneHelp: "Europe/Riga is used by default. You can change it in your profile.",
    savingAnalysis: "Finishing the secure account save first…", noEvents: "The document contains no precise future dates for which a reminder can be created.",
    date: "Date", dateMissing: "No exact date was found — check the document and enter it manually.", time: "Time", timeMissing: "The document does not contain an exact time — enter it manually.", eventTimezone: "Event time zone",
    remindWhen: "When to remind me", hour: "1 hour before", day: "24 hours before", week: "1 week before", month: "30 days before",
    defaultNote: "If you make no change, an exact date and time automatically uses the 24-hour option.",
    schedule: "Save reminder", scheduling: "Saving…", replace: "Change reminder", cancel: "Cancel", cancelling: "Cancelling…",
    scheduled: "Reminder scheduled", sent: "Reminder sent", failed: "Delivery failed", sending: "Reminder is being sent",
    willSend: "The email will be sent", noAvailableOffsets: "There is too little time left before the event for these options.",
    autoScheduled: "A 24-hour reminder was created automatically.", saved: "Reminder saved.", cancelled: "Reminder cancelled.",
    loadError: "Reminders could not be loaded. Try again later.", actionError: "The reminder could not be saved. Check the date and time.",
    pilot: "Reminders are currently in a closed pilot.", unavailable: "The reminder service is not configured yet.",
    sourceLanguage: "The email language follows the source document language.", verify: "Check the date and time against the original document.",
    profileTitle: "Email reminders", profileIntro: "Manage consent, your time zone, and upcoming emails.", enabled: "Allowed", disabled: "Off",
    disable: "Turn off and cancel future reminders", saveTimezone: "Save time zone", settingsSaved: "Settings saved.", upcoming: "Upcoming reminders", noneUpcoming: "No reminders are scheduled yet.",
  },
} satisfies Record<SupportedLanguage, Record<string, string>>;
